### ISSUE TITLE
View cant render

### ISSUE THREAD

**Issue by surayagami** [nulldev07/org-chart#4]
Hi,

Thanks for sharing this useful module.

I not sure why I cant render out the view as expected, the box and line are missing, hope you can help me on this.

![org-chart](https://user-images.githubusercontent.com/14244252/31041428-b235b642-a5c7-11e7-819d-b1c6e015fd38.png)

**Comment by soufianeGL** [comment]
Hi,
I think you should point to the css file to see if it exists. Or use custom css provided in the demo

**Comment by nulldev07** [comment]
Most probably the issue is the missing CSS.
